spring.application.name=onlineexam

# Server Port (Required for cloud platforms like Render/Heroku)
server.port=${PORT:28690}

# Database Configuration (Uses Cloud Env Variables if available, else localhost)
spring.datasource.url=${DB_URL:jdbc:mysql://mysql-2e6a9e1d-dspanand1977-dbcd.d.aivencloud.com:28690/defaultdb?ssl-mode=REQUIRED}
spring.datasource.username=${DB_USERNAME:avnadmin}
spring.datasource.password=${DB_PASSWORD:AVNS__TETdJE2s7TDHBcWD1n}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.cache=false
